proxmox:
  url: {{HOMEPAGE_VAR_PROXMOX_ADDRESS}}
  token: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
  secret: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}

edge:
  url: {{HOMEPAGE_VAR_EDGE_ADDRESS}}
  token: {{HOMEPAGE_VAR_EDGE_USERNAME}}
  secret: {{HOMEPAGE_VAR_EDGE_PASSWORD}}
